In [1]:
import pandas as pd
from numpy import isnan
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.neural_network import MLPClassifier


In [2]:
def get_training_dataset(binary=False):
    df = pd.read_csv('../UNSW-NB15/data/UNSW_NB15_training-set_cleaned.csv')
    labels = df.iloc[:, -1] if binary else df.iloc[:, -2]
    return df.iloc[:, 0:-2], labels

def get_testing_dataset(binary=False):
    df = pd.read_csv('../UNSW-NB15/data/UNSW_NB15_testing-set_cleaned.csv')
    labels = df.iloc[:, -1] if binary else df.iloc[:, -2]
    return df.iloc[:, 0:-2], labels

In [3]:
def test_mult_model(model):
    X_train, y_train = get_training_dataset()
    X_test, y_test = get_testing_dataset()

    model.fit(X_train, y_train)
    y_preds = model.predict(X_test)

    print(classification_report(y_test, y_preds))
    print(confusion_matrix(y_test, y_preds))

    return accuracy_score(y_test, y_preds), f1_score(y_test, y_preds, average="weighted")


In [4]:
def get_models():
    models = (MLPClassifier(random_state=13, max_iter=500),)

    for model in models:
      yield model

In [5]:
def print_results(accuracy, f1):
    print("")

    if not isnan(accuracy):
      print(f"\taccuracy: {accuracy}")
    if not isnan(f1):
      print(f"\tf1-score: {f1}")

def eval(model):
    print(f"{type(model).__name__}:")
    print_results(*test_mult_model(model))

In [6]:
model = get_models()

In [7]:
eval(next(model))

MLPClassifier:
              precision    recall  f1-score   support

           0       0.49      0.02      0.04      4089
           1       0.55      0.92      0.69     11132
           2       0.19      0.51      0.28      6062
           3       0.99      0.71      0.82     18871
           4       0.98      0.72      0.83     37000
           5       0.60      0.80      0.69      3496

    accuracy                           0.70     80650
   macro avg       0.63      0.61      0.56     80650
weighted avg       0.82      0.70      0.72     80650

[[   85  3622   178    28    10   166]
 [   50 10275   324    49    66   368]
 [    9  1821  3073    46   523   590]
 [    8   623  4861 13352     6    21]
 [   20  1753  7700    29 26809   689]
 [    1   671    35     0     7  2782]]

	accuracy: 0.6990204587724737
	f1-score: 0.7222469313800159
